[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "biopython>=1.86",
    "markitdown>=0.1.3",
    "openai>=2.8.1",
    "pandas>=2.3.3",
    "beautifulsoup4>=4.12.3",
    "python-docx>=1.2.0",
    "requests>=2.32.5",
    "spyprot>=0.9.6",
    "tabulate>=0.9.0",
    "tenacity>=9.1.2",
]
